#!/bin/bash

#
# run.sh - Driver for the CPSC411 Expression Language Compiler's passes
#

# Author: Norm Hutchinson
# Modified by Ron Garcia, 2016-2017
# Modified by Felipe Banados Schwerter, 2017

PROJECT=.
JARS="$PROJECT/backend/target/backend-1.0-SNAPSHOT.jar:\
$PROJECT/frontend/target/frontend-1.0-SNAPSHOT.jar:\
$PROJECT/ir/target/ir-1.0-SNAPSHOT.jar:\
$PROJECT/opt/target/opt-1.0-SNAPSHOT.jar:\
$PROJECT/x86_64sim/target/x86_64sim-1.0-SNAPSHOT.jar:\
$PROJECT/util/target/util-1.0-SNAPSHOT.jar"

CLASSPATH="$JARS"


if [ $# -ne 2 ]; then
   cat <<EOF ;
   Usage:
   run <CMD> file
   CMDs:
     parse, type, ir, gen, flow, interf, reg, final,
EOF
   exit 1;
fi

arg=
pass=$1
shift
export CLASSPATH
while [ 1 -le $# ] ; do
echo "Program: "
cat $1
echo ""
case $pass in
    ([Pp]ar*)
	pass=Parser  ;;
    ([Ff]low*)
	pass=FlowGraph ;;
    ([Gg]en* | [Cc]ode)
	pass=Generate ;;
    ([Ii]nt*)
	pass=Interference ;;
    ([Rr]eg*)
	pass=RegAlloc ;;
    ([Vv][Rr]eg*)
	pass=RegAlloc ; arg=-v;;
    ([Ff]inal*)
	pass=Final ;;
    ([Tt]ran* | [Ii][Rr]*)
	pass=Translate ;;
    ([Tt]ype* | [Cc]heck*)
	pass=TypeChecker ;;
    ([Ss]im[Ff]*)
	pass=SimFinal ;;
    ([Ss]im*)
	pass=Simulate ;;
    ([Ll]ive*)
	pass=Liveness ;;
    ([Rr]un* | [Ee]xec*)
	pass=Run ;;
    (*)
	echo "Don't understand $pass";
	exit 1;;
esac
java driver.D$pass $1 $arg
shift
done
