#!/bin/bash
PROJECT=.
IRPROJECT=../ir
FRONTENDPROJECT=../minijava-final
X8664PROJECT=../x86_64sim
ECLIPSEPLUGINS=/Applications/eclipse-juno/plugins
CLASSPATH=$PROJECT/bin:$IRPROJECT/bin:$X8664PROJECT/bin:$FRONTENDPROJECT/bin:$ECLIPSEPLUGINS/org.junit_4.10.0.v4_10_0_v20120426-0900/junit.jar:$ECLIPSEPLUGINS/org.hamcrest.core_1.1.0.v20090501071000.jar 
export CLASSPATH
arg=
pass=$1
shift
while [ 1 -le $# ] ; do
# echo "Program: "
# cat $1
# echo ""
case $pass in
    ([Aa][Ll][Ll])
	pass=oItAll  ;arg="parse= typecheck= translate=interpret,trace interpret= code=verbose register=veryverbose simulate= interference=verbose flow=verbose live=verbose";;
    ([Pp]ar*)
	pass=oItAll ; arg="parse=verbose" ;;
    ([Ff]low*)
	pass=oItAll ; arg="code= flow=verbose" ;;
    ([Gg]en* | [Cc]ode)
	pass=oItAll ; arg="code=verbose" ;;
    ([Ii]nt*)
	pass=oItAll ; arg="code= interference=verbose" ;;
    ([Ll]ive*)
	pass=oItAll ; arg="code= liveness=verbose" ;;
    ([Rr]eg*)
	pass=oItAll ; arg="register=verbose" ;;
    ([Vv][Rr]eg*)
	pass=oItAll ; arg="register=veryverbose" ;;
    ([Ff]inal*)
	pass=oItAll ; arg="dots=" ;;
    ([Tt]ran* | [Ii][Rr]*)
	pass=oItAll ; arg="translate=verbose,trace interpret=" ;;
    ([Tt]ype* | [Cc]heck*)
	pass=oItAll ; arg="typecheck=verbose" ;;
    ([Ss]im[Ff]*)
	pass=oItAll ; arg="register= simulate= dots=" ;;
    ([Ss]im*)
	pass=oItAll ; arg="simulate=" ;;
    ([Rr]un* | [Ee]xec*)
	pass=oItAll ; arg="register= dots= execute=" ;;
    (*)
	echo "Don't understand $pass";
	exit 1;;
esac
java driver.D$pass $1 $arg
shift
done
