#!/bin/bash
PROJECT=.
IRPROJECT=../ir
FRONTENDPROJECT=../minijava-final-newfrontend
ECLIPSEPLUGINS=/Applications/eclipse-juno/plugins
CLASSPATH=$PROJECT/bin:$IRPROJECT/bin:$FRONTENDPROJECT/bin:$ECLIPSEPLUGINS/org.junit_4.10.0.v4_10_0_v20120426-0900/junit.jar:$ECLIPSEPLUGINS/org.hamcrest.core_1.1.0.v20090501071000.jar 
export CLASSPATH
arg=
pass=$1
shift
while [ 1 -le $# ] ; do
echo "Program: "
cat $1
echo ""
case $pass in
    ([Pp]ar*)
	pass=Parser  ;;
    ([Ff]low*)
	pass=FlowGraph ;;
    ([Aa]vail*)
	pass=AvailableExpressions ;;
    ([Vv][Aa]vail*)
	pass=AvailableExpressions ; arg=-v ;;
    ([Rr]each*)
	pass=ReachingDefinitions ;;
    ([Vv][Rr]each*)
	pass=ReachingDefinitions ; arg=-v ;;
    ([Gg]en* | [Cc]ode)
	pass=Generate ;;
    ([Ii]nt*)
	pass=Interference ;;
    ([Ll]ive*)
	pass=Liveness ;;
    ([Dd]ead*)
	pass=DeadCode ;;
    ([Cc]onst[Dd]ead*)
	pass=ConstantPropagationDeadCode ;;
    ([Cc]onst*)
	pass=ConstantPropagation ;;
    ([Pp]eep*)
	pass=Peephole ;;
    ([Oo][Rr]eg* | [Oo]pt*[Rr]eg*)
	pass=OptRegAlloc ;;
    ([Oo]pt*)
	pass=Opt ;;
    ([Dd]om*)
	pass=Dominators ;;
    ([Rr]eg*)
	pass=RegAlloc ;;
    ([Vv][Rr]eg*)
	pass=RegAlloc ; arg=-v;;
    ([Ff]inal*)
	pass=Final ;;
    ([Tt]ran* | [Ii][Rr]*)
	pass=Translate ;;
    ([Tt]ype* | [Cc]heck*)
	pass=TypeChecker ;;
    ([Ss]im[Ff]*)
	pass=SimFinal ;;
    ([Ss]im*)
	pass=Simulate ;;
    ([Rr]un* | [Ee]xec*)
	pass=Run ;;
    (*)
	echo "Don't understand $pass";
	exit 1;;
esac
java driver.D$pass $1 $arg
shift
done
